# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: Task5@0
  inputs:
    script: Write-Host "Hello, world!"
              $myVariable = "some name"
          $myValue = "some value"
            $myVariableNewValue = '##vso[task.setvariable variable=myVariable]' + $newValue
            Write-Host $myVariableNewValue
