# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: Task1@0
  inputs:
    displayName: 'Install SFDX Cli'
    targetType: 'inline'
    script: |
      echo 'Installing sfdx cli'
       npm install -g sfdx-cli
      echo 'Installing sfdx git delta'
       echo y | sfdx plugins:install sfdx-git-delta
- task: Task2@0
  inputs:
    displayName: 'Get previous commit Id'
    targetType: 'inline'
    script: |
      $prevCommitId=$(git rev-parse HEAD^)
      Write-Host 'Id : $prevCommitId'
      Write-Host '##vso[task.setvariable variable=prevCommitId;isOutput=true]$prevCommitId'
