# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
parameters: 
- name: CommitID
  displayName: Commit ID
  type: string
  default: ' '
- name: DeploymentType
  displayName: Deployment Type
  type: string  
  default: 'Delta' 
  values:
  - Delta
  - Src   
- name: AppNames
  displayName: Application Names
  type: string
  default: 'ALL'  
- name: Excluded
  displayName: Excluded Files/Folders  
  type: string
  default: ' '  
variables:
  COMMIT_ID: ${{ parameters.CommitID }}  
  ExcludedFiles: ${{ parameters.Excluded }} 
steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'


- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: Task1@0
  inputs:
    script: |
      echo 'Installing sfdx cli'
      # npm install -g sfdx-cli
      # echo 'Installing sfdx git delta'
      # echo y | sfdx plugins:install sfdx-git-delta
- task: Task2@0
  condition: and(succeeded(), eq('${{ parameters.DeploymentType }}', 'Delta'))
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
    IgnoreFiles: $(ExcludedFiles)
  inputs:
    script: |
      $pat = "46ueei7hseaok2gandqnzuyxwbi5rfkahl3kl32szymfxpj4kupq"
      $token = [System.Convert]::ToBase64String([System.Text.Encoding]::ASCII.GetBytes(":$($pat)"))
      $header = @{Authorization = "Basic $token"}
      $url = "https://vsrm.dev.azure.com/sivaranjaniminuscule/Salesforce%20Demo/_apis/release/deployments?deploymentStatus=succeeded&definitionId=2&definitionEnvironmentId=2&queryOrder=descending?api-version=6.0"
      try {
        $response = Invoke-RestMethod -Uri $url -Method Get -Headers $header #| ConvertTo-Json > release.json
        Get-Content ./release.json
        $releaseCount = $response.count
        Write-Host "Total Release : $releaseCount"
          }
       Catch {    
         Write-Host "Error occured : $_"
       }